--1-What is the total sales revenue for the entire period?
select sum(total_amount) from fact_sales;

--2-What are the total sales revenues for each year?
select year(sales_date) as year, sum(total_amount) as "total sales"
from fact_sales
group by year(sales_date);

--3-What is the total sales quantity and revenue for each quarter?
select d.quarter, sum(f.total_amount) as "total sales"
from fact_sales f
join dim_dates d
    on f.date_sk = d.date_sk
group by quarter
order by quarter;

--4-What is the average sales revenue per transaction?
select avg(total_amount)
from fact_sales

--5-What is the total profit for each month, and how is it calculated?
select d.month, sum(f.total_amount) as "total sales"
from fact_sales f
join dim_dates d
    on f.date_sk = d.date_sk
group by month
order by month;
--summing total amount of each month joining dim_date with the fact_sales

--6-What are the top 10 customers by total sales revenue?
select d.customer_sk, min(concat(d.first_name, ' ', d.last_name)) as customer_name,
        sum(f.total_amount) as total_amount
from fact_sales f
join dim_customers d
    on f.CUSTOMER_SK = d.customer_sk
group by d.customer_sk
order by total_amount desc
limit 10;

--7-How many unique customers made a purchase each year?
select year(sales_date) as Year, count(distinct customer_sk) as "Number of customers"
from fact_sales
group by year(sales_date);

--8-What is the gender distribution of customers?
-- a custom REGEX gives 70-85%
select
  case
    when (lower(trim(first_name))) rlike '.*[aeioy]$|.*ey$|.*ie$|.*lyn$' then 'female'
    else 'male'
  end as gender,
  count(*) as customer_count,
  round((count(*) * 100.0 / sum(count(*)) over()), 2) as percentage
from dim_customers
group by 1
order by customer_count desc;

--9-What is the average age of customers in each city?

--10-What is the total sales revenue by customer state?
select d.RESIDENTIAL_LOCATION as state,
        sum(f.total_amount) as "total sales"
from fact_sales f
join dim_customers d
    on f.customer_sk = d.customer_sk
group by state
order by sum(f.total_amount) desc;

--11-What are the top 5 product categories by sales revenue?
select d.product_sk,
        max(d.product_name) as product_name,
        sum(f.total_amount) as total_amount
from fact_sales f
join dim_products d
    on f.product_sk = d.product_sk
group by d.product_sk
order by total_amount desc
limit 5;

--12-Which product has the highest sales quantity?
select max(d.product_name) as product_name,
        count(f.product_sk) as transactions
from fact_sales f
join dim_products d
    on f.product_sk = d.product_sk
group by d.product_sk
order by count(f.product_sk) desc
limit 1;


--13-What is the total revenue for each product sub-category?
select max(d.category), sum(f.total_amount)
from fact_sales f
join dim_products d
    on f.product_sk = d.product_sk
group by d.category
order by sum(f.total_amount) desc;

--14-What are the products with the lowest profit margin?
select max(d.product_name), sum(f.total_amount)
from fact_sales f
join dim_products d
    on f.product_sk = d.product_sk
group by f.product_sk
order by sum(f.total_amount);

--15-What percentage of total sales does each product category represent?
select max(d.CATEGORY),
        sum(f.total_amount),
        round(sum(f.total_amount) * 100.0 / sum(sum(f.total_amount)) over (), 2) as percentage
from fact_sales f
join dim_products d
    on f.product_sk = d.product_sk
group by d.category
order by percentage desc;

--16-What is the average shipping cost per transaction for each country?
select max(d.store_name) as store_name,
        sum(f.total_amount) as total_amount,
        count(f.store_sk) as quantity
from fact_sales f
join dim_stores d
    on f.store_sk = d.store_sk
group by d.store_sk
order by sum(f.total_amount) desc;

--17-What is the average shipping cost per transaction for each country?
--18-Which store had the most transactions?
select max(d.store_name) as store_name,
        count(f.store_sk) as transactions
from fact_sales f
join dim_stores d
    on f.store_sk = d.store_sk
group by d.store_sk
order by count(f.store_sk) desc
limit 1;

--19-What is the total sales revenue by store state?
select max(d.store_location) as store_location,
        sum(f.total_amount) as total_amount        
from fact_sales f
join dim_stores d
    on f.store_sk = d.store_sk
group by d.store_location
order by sum(f.total_amount) desc;

--20-What is the average sales revenue per store?
select max(d.store_location) as store_location,
        avg(f.total_amount) as total_amount        
from fact_sales f
join dim_stores d
    on f.store_sk = d.store_sk
group by d.store_location
order by avg(f.total_amount) desc;

--21-What is the total sales revenue generated by each salesperson?
select max(d.salesperson_name) as salesperson_name,
        sum(f.total_amount) as total_amount        
from fact_sales f
join dim_salesperson d
    on f.salesperson_sk = d.salesperson_sk
group by d.salesperson_sk
order by sum(f.total_amount) desc;

--22-How many unique customers were part of each campaign?
select d.campaign_name, count(distinct f.customer_sk) as unique_customer_per_campaign
from fact_sales f
join dim_campaigns d
    on f.campaign_sk = d.campaign_sk
group by d.campaign_name;

--23-Which salesperson generated the highest profit?
select max(d.salesperson_name) as salesperson_name,
        sum(f.total_amount) as total_amount        
from fact_sales f
join dim_salesperson d
    on f.salesperson_sk = d.salesperson_sk
group by d.salesperson_sk
order by sum(f.total_amount) desc
limit 1;

--24-What is the average sales revenue for transactions associated with a campaign?
select d.campaign_name, 
        round(avg(f.total_amount), 2) as avg_sales
from fact_sales f
join dim_campaigns d
    on f.campaign_sk = d.campaign_sk
group by d.campaign_name
order by avg_sales;

--25-What is the total sales revenue by salesperson region?

--26-How did total sales revenue change year-over-year?
select year(sales_date) as year,
        sum(total_amount) as total_sales,
        lag(sum(total_amount)) over (order by year(sales_date)) as prev_sales_date,
        sum(total_amount) - lag(sum(total_amount)) over (order by year(sales_date))
        * 100.0 / nullif(lag(sum(total_amount)) over (order by year(sales_date)), 0)
        as yoy_change_percentage
from fact_sales
group by year(sales_date)
order by year;

--27-What is the month-over-month sales growth percentage for the current year?
select 
    month(sales_date) as month,
    sum(total_amount) as total_sales,
    lag(sum(total_amount)) over (order by month(sales_date)) as prev_sales,
    (sum(total_amount) - lag(sum(total_amount)) over (order by month(sales_date)))
    * 100.0 / nullif(lag(sum(total_amount)) over (order by month(sales_date)), 0)
    as mom_change_percentage
from fact_sales
group by month(sales_date)
order by month;

--28-How does product category performance vary across different regions?
select p.category,
        s.store_location,
        sum(f.total_amount)
from fact_sales f
join dim_products p
    on f.product_sk = p.product_sk
join dim_stores s 
    on f.store_sk = s.store_sk
group by p.category, s.store_location
order by p.category

--29-What is the average sales revenue and quantity per customer per store?
select max(c.first_name) as customer_name,
        max(s.store_name) as store_name,
        avg(total_amount) as avg_sales,
        count(f.customer_sk) as quantity
from fact_sales f
join dim_customers c
    on f.customer_sk = c.customer_sk
join dim_stores s
    on f.store_sk = s.store_sk
group by f.customer_sk
order by quantity desc;

--30-What is the total sales revenue by transaction type?
